export interface ProjectLink {
  href: string;
  label: string;
}

export interface Project {
  slug: string;
  name: string;
  category: 'Social' | 'Decentralized' | 'DeFi' | 'AI & NLP' | 'Education' | 'Sustainability' | 'Health' | 'Infrastructure' | 'Tools & Utilities' | 'Ready to download' | 'Production ready' | 'Ongoing';
  status: 'Ongoing' | 'Production Ready' | 'Active Development' | 'production' | 'ongoing';
  shortDescription: string;
  fullDescription: string;
  keyFeatures: string[];
  techStack: string[];
  logo: string;
  githubLink: string;
  discordLink: string;
  downloadLink?: string;
  websiteUrl?: string;
  link?: ProjectLink;
}

export const PROJECTS_DATA: Project[] = [
  {
    slug: 'dit',
    name: 'DIT (Decentralized Identity & Trust)',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: 'A framework for building verifiable decentralized identity, trust metrics, and transparent credentialing.',
    fullDescription: 'DIT (Decentralized Identity & Trust) provides cryptographic infrastructure for digital identity verification. It allows individuals and organizations to issue, hold, and verify decentralized credentials without relying on single point-of-failure certificate authorities.',
    keyFeatures: ['Self-Sovereign Identity (SSI) Standards', 'Zero-Knowledge Proof Credential Verification', 'Interoperable Decentralized Identifiers (DIDs)', 'Tamper-Proof Audit Trails'],
    techStack: ['TypeScript', 'Solidity', 'Rust', 'Cryptographic Primitives'],
    logo: '/brand/project_svgs/dit_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/DIT',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/DIT', label: 'DIT' }
  },
  {
    slug: 'fate',
    name: 'FATE',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'Fairness, Accountability, Transparency, and Ethics in Artificial Intelligence models and datasets.',
    fullDescription: 'FATE is an open-source toolkit for auditing machine learning models for bias, opacity, and ethical alignment. It provides data scientists and developers with metrics, visual diagnostics, and automated reports to ensure AI systems operate fairly and transparently.',
    keyFeatures: ['Algorithmic Bias Mitigation Metrics', 'Explainable AI Model Diagnostics', 'Automated Fairness Audit Reporting', 'Dataset Representation Profiling'],
    techStack: ['Python', 'PyTorch', 'scikit-learn', 'FastAPI', 'React'],
    logo: '/brand/project_svgs/fate_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/FATE',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/FATE', label: 'FATE' }
  },
  {
    slug: 'thrubox',
    name: 'Thrubox',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: 'A secure, decentralized storage gateway leveraging IPFS and file-coin protocols.',
    fullDescription: 'Thrubox enables users to upload, encrypt, and store files on decentralized storage networks seamlessly. It bridges IPFS networks with accessible web interfaces and user authentication.',
    keyFeatures: ['Client-Side End-to-End Encryption', 'IPFS & Filecoin Storage Pinning Integration', 'Decentralized Access Control', 'Fast Content Delivery Network Nodes'],
    techStack: ['TypeScript', 'IPFS', 'Next.js', 'Tailwind CSS'],
    logo: '/brand/project_svgs/thrubox_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Thrubox',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Thrubox', label: 'Thrubox' }
  },
  {
    slug: 'skills',
    name: 'Open Skills',
    category: 'Education',
    status: 'ongoing',
    shortDescription: 'An open educational platform for mapping tech competencies, skill trees, and open-source learning pathways.',
    fullDescription: 'Open Skills empowers learners, educators, and open-source contributors to visualize skill trees, track learning milestones, and match competencies with real-world open-source issues and projects.',
    keyFeatures: ['Interactive Competency & Skill Tree Visualization', 'Automated Repository Issue Skill Matching', 'Open Credential Badging', 'Community Learning Pathway Curation'],
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'GraphQL'],
    logo: '/brand/project_svgs/skills_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Skills',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Skills', label: 'Skills' }
  },
  {
    slug: 'moveyourbody',
    name: 'MoveYourBody',
    category: 'Health',
    status: 'ongoing',
    shortDescription: 'An open-source privacy-first posture and workout tracking application using computer vision.',
    fullDescription: 'MoveYourBody leverages lightweight web-based computer vision to help users maintain ergonomic posture and follow exercise routines without transmitting camera feeds to external servers.',
    keyFeatures: ['On-Device TensorFlow.js Pose Estimation', 'Zero-Data Transmission Privacy Architecture', 'Custom Ergonomic Posture Alerts', 'Interactive Fitness Analytics'],
    techStack: ['React', 'TensorFlow.js', 'WebGPU', 'Tailwind CSS'],
    logo: '/brand/project_svgs/MoveYourBody_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/MoveYourBody',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/MoveYourBody', label: 'MoveYourBody' }
  },
  {
    slug: 'minichain',
    name: 'MiniChain',
    category: 'Infrastructure',
    status: 'ongoing',
    shortDescription: 'A lightweight educational blockchain implementation designed to demonstrate consensus, P2P networking, and state execution.',
    fullDescription: 'MiniChain is an educational blockchain engine built from scratch. It serves as a practical codebase for students and developers learning about Proof-of-Work, Proof-of-Stake, cryptographic hashing, and peer-to-peer gossip protocols.',
    keyFeatures: ['Clean Modular P2P Gossip Network Layer', 'Configurable Consensus Engines', 'Visual Block Explorer', 'Educational Documentation'],
    techStack: ['Go', 'TypeScript', 'Node.js', 'WebSockets'],
    logo: '/brand/project_svgs/minichain_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/MiniChain',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/MiniChain', label: 'MiniChain' }
  },
  {
    slug: 'open-gift-hub',
    name: 'Open Gift Hub',
    category: 'Social',
    status: 'ongoing',
    shortDescription: 'A community platform for open-source project gifting, micro-sponsorships, and peer recognition.',
    fullDescription: 'Open Gift Hub enables open-source maintainers and contributors to receive transparent micro-sponsorships, digital gifts, and peer recognition without heavy platform commissions.',
    keyFeatures: ['Transparent Peer-to-Peer Micro-Funding', 'GitHub Integration for Recognition', 'Customizable Digital Badges', 'Zero Platform Fee Model'],
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Stripe/Web3 API'],
    logo: '/brand/project_svgs/ogh_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Ogh',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Ogh', label: 'Ogh' }
  },
  {
    slug: 'pictopy',
    name: 'PicToPy',
    category: 'AI & NLP',
    status: 'production',
    shortDescription: 'PicToPy is a modern desktop app designed to transform the handling of digital photos. It facilitates efficient gallery management with a robust focus on privacy.',
    fullDescription: 'PicToPy is an open-source Python desktop application and library for intelligent photo organization and privacy-preserving face recognition. It helps users sort, organize, and search through large image collections locally on their computer.',
    keyFeatures: ['100% Offline Local AI Processing', 'Facial Recognition & Object Tagging', 'EXIF Metadata Batch Editing', 'Cross-Platform Desktop Application'],
    techStack: ['Python', 'PyQt5', 'OpenCV', 'face_recognition'],
    logo: '/brand/project_svgs/pictopy_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/PicToPy',
    downloadLink: 'https://github.com/AOSSIE-Org/PicToPy/releases',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/PicToPy', label: 'PicToPy' }
  },
  {
    slug: 'agora-vote-android',
    name: 'Agora Vote Android',
    category: 'Decentralized',
    status: 'production',
    shortDescription: 'This application uses Agora Web API as backend application. It allows for elections to be held by using multiple algorithms.',
    fullDescription: 'Agora Vote Android is a mobile electronic voting system. It allows organizations to host secure elections using a wide variety of voting algorithms, ranging from Preferential Voting to Schulze and STV methods.',
    keyFeatures: ['Multi-Algorithm Election Support', 'Verifiable Ballot Encryption', 'Android Native Interface', 'Agora API Integration'],
    techStack: ['Kotlin', 'Android SDK', 'Java', 'Agora API'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://gitlab.com/aossie/agora-android',
    downloadLink: 'https://gitlab.com/aossie/agora-android/-/releases',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://gitlab.com/aossie/agora-android', label: 'Agora-Android' }
  },
  {
    slug: 'djed',
    name: 'Djed',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'Djed is a Formally Verified Crypto-Backed Algorithmic Stablecoin Protocol.',
    fullDescription: 'Djed is an algorithmic stablecoin protocol that behaves like an autonomous bank that buys and sells stablecoins for a price within a range that is pegged to a target price.',
    keyFeatures: ['Formally Verified Smart Contracts', 'Algorithmic Peg Maintenance', 'Reserve Ratio Bounds Enforcement', 'Multi-Asset Collateral Pool'],
    techStack: ['Solidity', 'ErgoScript', 'TypeScript', 'Web3.js'],
    logo: '/brand/project_svgs/djed_alliance_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Djed-Solidity-WebDashboard',
    downloadLink: 'https://github.com/AOSSIE-Org/Djed-Solidity-WebDashboard',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Djed-Solidity-WebDashboard', label: 'Djed' }
  },
  {
    slug: 'devr-ai',
    name: 'Devr.AI',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'An open-source AI-powered platform designed to automate and enhance developer relations using agentic workflows.',
    fullDescription: 'Devr.AI leverages Generative AI and agentic workflows to streamline community engagement, developer support, pull request analysis, and open-source project outreach.',
    keyFeatures: ['Agentic Developer Support Workflows', 'Automated Pull Request Code Review', 'Community Analytics', 'Open-Weight LLM Orchestration'],
    techStack: ['Python', 'FastAPI', 'LangChain', 'React'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Devr.AI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Devr.AI', label: 'Devr.AI' }
  },
  {
    slug: 'rein',
    name: 'Rein',
    category: 'Tools & Utilities',
    status: 'ongoing',
    shortDescription: 'A cross-platform LAN-based remote input controller that allows users to control devices over a local network seamlessly.',
    fullDescription: 'Rein provides low-latency input virtualization, enabling smartphone and desktop input sharing over local WiFi networks with zero cloud server dependency.',
    keyFeatures: ['Zero-Server Local LAN Discovery', 'Ultra-Low Latency Input Emulation', 'Cross-Platform Companion Apps', 'Encrypted P2P Channels'],
    techStack: ['Rust', 'Flutter', 'TypeScript', 'WebSockets'],
    logo: '/brand/project_svgs/rein_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Rein',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Rein', label: 'Rein' }
  },
  {
    slug: 'open-verifiable-llm',
    name: 'OpenVerifiableLLM',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'Local Fully Open, Open-Weight, Open-Data, Verifiable LLMs. A project focused on building transparent and trustworthy large language models.',
    fullDescription: 'OpenVerifiableLLM focuses on building transparent, reproducible, and verifiable language models, allowing researchers to inspect training datasets, weights, and inference outputs.',
    keyFeatures: ['Verifiable Inference Proofs', 'Open Training Corpora & Weights', 'On-Device Execution', 'Safety Diagnostic Suite'],
    techStack: ['Python', 'PyTorch', 'Transformers', 'CUDA'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/OpenVerifiableLLM',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/OpenVerifiableLLM', label: 'OpenVerifiableLLM' }
  },
  {
    slug: 'libred',
    name: 'LibrEd',
    category: 'Education',
    status: 'production',
    shortDescription: 'A self-learning assistant that helps users learn and study more effectively using AI-powered tools and personalized learning paths.',
    fullDescription: 'LibrEd delivers interactive flashcards, spaced repetition schedules, and personalized educational pathways to accelerate self-directed learning.',
    keyFeatures: ['AI Flashcard Generation', 'Spaced Repetition Algorithm', 'Progress Analytics', 'Offline Study Mode'],
    techStack: ['React', 'Next.js', 'Python', 'Tailwind CSS'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/LibrEd',
    downloadLink: 'https://github.com/AOSSIE-Org/LibrEd/releases',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/LibrEd', label: 'LibrEd' }
  },
  {
    slug: 'websift',
    name: 'WebSift',
    category: 'Tools & Utilities',
    status: 'ongoing',
    shortDescription: 'A tool to convert webpages to MML-ready formats, enabling seamless extraction and transformation of web content for machine learning pipelines.',
    fullDescription: 'WebSift parses complex DOM structures into clean JSON and Markdown datasets optimized for training and fine-tuning machine learning models.',
    keyFeatures: ['DOM Cleaning', 'Structured Markdown Extraction', 'Batch Web Crawler', 'API & CLI Interfaces'],
    techStack: ['Python', 'BeautifulSoup', 'Node.js', 'Puppeteer'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/WebSift',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/WebSift', label: 'WebSift' }
  },
  {
    slug: 'inpact-ai',
    name: 'InPactAI',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'An open-source AI-powered platform designed to connect content creators, brands, and agencies through data-driven insights leveraging Generative AI.',
    fullDescription: 'InPactAI leverages generative AI analytics to help open-source projects and creators measure content reach, audience engagement, and campaign authenticity.',
    keyFeatures: ['Creator Analytics Dashboard', 'AI Sentiment Profiling', 'Automated Performance Reports', 'Open Data Integrations'],
    techStack: ['Next.js', 'Python', 'FastAPI', 'Tailwind CSS'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/InPactAI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/InPactAI', label: 'InPactAI' }
  },
  {
    slug: 'babynest',
    name: 'BabyNest',
    category: 'Health',
    status: 'ongoing',
    shortDescription: "A comprehensive baby care and tracking application that helps parents monitor and manage their baby's daily activities, milestones, and health.",
    fullDescription: 'BabyNest provides parents with a secure, privacy-first logbook for tracking growth charts, feeding schedules, vaccination reminders, and developmental milestones.',
    keyFeatures: ['Growth Percentile Tracking', 'Vaccination Reminders', 'Encrypted Local Sync', 'Mobile Interface'],
    techStack: ['React Native', 'TypeScript', 'SQLite'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/BabyNest',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/BabyNest', label: 'BabyNest' }
  },
  {
    slug: 'smartnotes',
    name: 'SmartNotes',
    category: 'Tools & Utilities',
    status: 'ongoing',
    shortDescription: 'An intelligent note-taking application that leverages AI to help users organize, search, and manage their notes more effectively.',
    fullDescription: 'SmartNotes automatically tags, categorizes, and links notes together using semantic embeddings, providing instantaneous semantic search across personal knowledge bases.',
    keyFeatures: ['Semantic Vector Search', 'Auto-Summarization', 'Markdown Editor', 'Cross-Device Sync'],
    techStack: ['Electron', 'React', 'TypeScript', 'VectorDB'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/SmartNotes',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/SmartNotes', label: 'SmartNotes' }
  },
  {
    slug: 'orgexplorer',
    name: 'OrgExplorer',
    category: 'Tools & Utilities',
    status: 'ongoing',
    shortDescription: 'An intuitive dashboard to explore large GitHub organizations, providing insights into repositories, contributors, and activity metrics.',
    fullDescription: 'OrgExplorer visualizes open-source activity across GitHub organizations, identifying active contributors, PR throughput, issue velocity, and repository health metrics.',
    keyFeatures: ['Interactive Charts', 'Contributor Leaderboards', 'PR & Issue Analytics', 'GitHub GraphQL Engine'],
    techStack: ['Next.js', 'Chart.js', 'TypeScript', 'GraphQL'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/OrgExplorer',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/OrgExplorer', label: 'OrgExplorer' }
  },
  {
    slug: 'ell-ena',
    name: 'Ell-ena',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'A smart AI product manager that streamlines task, project, and meeting management through a simple chat interface.',
    fullDescription: 'Ell-ena acts as a virtual project manager, helping open-source teams break down issues, draft meeting minutes, assign tasks, and summarize discussion threads.',
    keyFeatures: ['Conversational Task Management', 'Meeting Minutes Extraction', 'Issue Decomposition', 'GitHub & Discord Integration'],
    techStack: ['Python', 'HuggingFace', 'FastAPI', 'Node.js'],
    logo: '/brand/project_svgs/ellena_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Ell-ena',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Ell-ena', label: 'Ell-ena' }
  },
  {
    slug: 'zplit',
    name: 'Zplit',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A payment splitting app that makes it easy to divide expenses among groups, track balances, and settle debts.',
    fullDescription: 'Zplit makes sharing expenses simple for groups traveling or managing shared funds. Users can log expenses in fiat or crypto and settle balances instantly on-chain.',
    keyFeatures: ['Instant Group Expense Calculation', 'On-Chain Settlement', 'Gas-Optimized Batching', 'Mobile-Responsive UI'],
    techStack: ['React', 'Solidity', 'Tailwind CSS', 'Vite'],
    logo: '/brand/project_svgs/zplit_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Zplit',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Zplit', label: 'Zplit' }
  },
  {
    slug: 'docpilot',
    name: 'DocPilot',
    category: 'Health',
    status: 'ongoing',
    shortDescription: 'A new age EMR (Electronic Medical Records) application using conversational AI at its best, streamlining healthcare documentation.',
    fullDescription: 'DocPilot helps physicians transcribe, structure, and query medical records using privacy-compliant local conversational AI models.',
    keyFeatures: ['Voice-to-Text Transcription', 'Structured EMR Generation', 'Privacy Compliance Architecture', 'Clinical Support Prompts'],
    techStack: ['Python', 'React', 'FastAPI', 'Whisper'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/DocPilot',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/DocPilot', label: 'DocPilot' }
  },
  {
    slug: 'perspective',
    name: 'Perspective',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'A tool for analyzing and understanding different perspectives on topics, enabling balanced and informed viewpoints.',
    fullDescription: 'Perspective extracts diverse viewpoints, arguments, and counter-arguments on controversial topics from news corpora and research papers using NLP models.',
    keyFeatures: ['Multi-Perspective Claim Extraction', 'Stance Detection', 'Interactive Argument Maps', 'Research Dataset Integration'],
    techStack: ['Python', 'PyTorch', 'React', 'FastAPI'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Perspective',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Perspective', label: 'Perspective' }
  },
  {
    slug: 'neurotrack',
    name: 'NeuroTrack',
    category: 'Health',
    status: 'ongoing',
    shortDescription: 'A neuroscience-focused tracking application for monitoring and analyzing neural activity and cognitive performance.',
    fullDescription: 'NeuroTrack provides researchers with tools to record, filter, and visualize EEG and motor signals for cognitive workload research.',
    keyFeatures: ['Real-Time Signal Filtering', 'Cognitive Workload Index', 'Hardware Sensor Support', 'ML Data Export'],
    techStack: ['Python', 'MNE-Python', 'React', 'WebSockets'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/NeuroTrack',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/NeuroTrack', label: 'NeuroTrack' }
  },
  {
    slug: 'codingagent',
    name: 'CodingAgent',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'An AI-powered coding agent that assists developers with code generation, debugging, and software development tasks.',
    fullDescription: 'CodingAgent connects directly to repository file trees to autonomously fix failing unit tests, refactor legacy functions, and write inline documentation.',
    keyFeatures: ['Autonomous Test Refactoring', 'AST Code Analysis', 'Multi-File Edit Engine', 'Local LLM Support'],
    techStack: ['TypeScript', 'Node.js', 'Python', 'LLM APIs'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/CodingAgent',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/CodingAgent', label: 'CodingAgent' }
  },
  {
    slug: 'starcross',
    name: 'Starcross',
    category: 'Education',
    status: 'ongoing',
    shortDescription: 'An astronomy application that helps users explore and identify celestial objects, constellations, and astronomical events.',
    fullDescription: 'Starcross renders 3D interactive star charts, planetary orbits, and satellite passes using WebGL for students and astronomy enthusiasts.',
    keyFeatures: ['3D Celestial Sphere Render', 'Satellite Pass Calculations', 'Constellation Catalog', 'WebGL Graphics'],
    techStack: ['Three.js', 'TypeScript', 'React', 'WebGL'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/starcross',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/starcross', label: 'Starcross' }
  },
  {
    slug: 'carbon-footprint',
    name: 'CarbonFootprint',
    category: 'Sustainability',
    status: 'ongoing',
    shortDescription: 'A browser extension that helps users track and reduce their carbon footprint by displaying CO2 emissions for various activities.',
    fullDescription: 'CarbonFootprint inserts real-time CO2 estimates directly onto Google Maps routes, flight search engines, and online shopping carts.',
    keyFeatures: ['Google Maps Route Emission Overlay', 'Mode of Transport Comparisons', 'Personal Carbon Offset Goals', 'Open Data Engine'],
    techStack: ['JavaScript', 'WebExtensions API', 'Chart.js'],
    logo: '/brand/project_svgs/carbonTracker_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/CarbonFootprint',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/CarbonFootprint', label: 'CarbonFootprint' }
  },
  {
    slug: 'mind-the-word',
    name: 'MindTheWord',
    category: 'Education',
    status: 'ongoing',
    shortDescription: 'A browser extension for language learning that randomly translates words on webpages to help users learn new languages while browsing.',
    fullDescription: 'MindTheWord helps users learn new languages effortlessly by immersing them in foreign vocabulary while reading everyday articles.',
    keyFeatures: ['Context-Aware Word Translation', 'Customizable Target Languages', 'Flashcard Vocabulary Lists', 'Translation API Integration'],
    techStack: ['JavaScript', 'WebExtensions API', 'CSS3'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/MindTheWord',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/MindTheWord', label: 'MindTheWord' }
  },
  {
    slug: 'aossie-scholar',
    name: 'Aossie Scholar',
    category: 'Education',
    status: 'ongoing',
    shortDescription: 'An academic search and research tool that helps scholars discover, organize, and analyze academic papers and publications.',
    fullDescription: 'Aossie Scholar aggregates open-access research papers, visualizes citation networks, and extracts key findings across computer science and mathematics.',
    keyFeatures: ['Citation Graph Visualization', 'Open Access PDF Parsing', 'Research Topic Categorization', 'Exportable BibTeX Records'],
    techStack: ['React', 'Python', 'FastAPI', 'D3.js'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Aossie-Scholar',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Aossie-Scholar', label: 'Aossie-Scholar' }
  },
  {
    slug: 'agora-blockchain',
    name: 'Agora Blockchain',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: "There isn't just one voting algorithm, there's hundreds. Therefore, we developed Agora to allow for democratic elections using any algorithm.",
    fullDescription: 'Agora Blockchain provides cryptographically secure, tamper-proof voting infrastructure supporting preferential, STV, Borda, and Schulze counting methods.',
    keyFeatures: ['Zero-Knowledge Vote Secrecy', 'On-Chain Ballot Verification', 'Pluggable Voting Engines', 'Audit Trail Generation'],
    techStack: ['Solidity', 'Rust', 'TypeScript', 'Next.js'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Agora-Blockchain',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Agora-Blockchain', label: 'Agora' }
  },
  {
    slug: 'eduaid',
    name: 'EduAid',
    category: 'Education',
    status: 'ongoing',
    shortDescription: 'An online tool that can generate short quizzes on input educational content can be of great use to teachers and students alike as it can help retain important information, frame questions and quickly revise large chunks of content.',
    fullDescription: 'EduAid automatically creates multiple-choice questions, short answers, and study flashcards from textbook text and lecture slides.',
    keyFeatures: ['Automated Quiz Generation', 'Difficulty Level Adjustment', 'Export to Study Tools', 'Textbook PDF Parsing'],
    techStack: ['Python', 'React', 'FastAPI', 'HuggingFace'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/EduAid',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/EduAid', label: 'EduAid' }
  },
  {
    slug: 'openchat',
    name: 'OpenChat',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: 'A decentralised platform for secure and private messaging and file sharing built on top of blockchain.',
    fullDescription: 'OpenChat delivers end-to-end encrypted peer-to-peer communication without central servers or phone number requirements.',
    keyFeatures: ['End-to-End Encrypted P2P Channels', 'Decentralized File Storage', 'Self-Sovereign Identity Login', 'Zero Server Log Architecture'],
    techStack: ['React', 'WebRTC', 'Solidity', 'LibP2P'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/OpenChat',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/OpenChat', label: 'OpenChat' }
  },
  {
    slug: 'resonate',
    name: 'Resonate',
    category: 'Social',
    status: 'ongoing',
    shortDescription: 'With the rising popularity of social voice platforms such as Clubhouse, it is high time for an Open Source alternative. A platform like this would not only enhance credibility within the open-source community but also attract more users and foster growth.',
    fullDescription: 'Resonate is an innovative open-source social audio platform built to give users control over their data, voice conversations, and digital identities.',
    keyFeatures: ['Real-time P2P Audio Streaming', 'Decentralized Identity', 'Community Moderation', 'Cross-Platform Web/Mobile'],
    techStack: ['React', 'Next.js', 'WebRTC', 'Node.js'],
    logo: '/brand/project_svgs/resonate_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Resonate',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    websiteUrl: 'https://resonate.aossie.org',
    link: { href: 'https://github.com/AOSSIE-Org/Resonate', label: 'Resonate' }
  },
  {
    slug: 'monumento',
    name: 'Monumento',
    category: 'Social',
    status: 'ongoing',
    shortDescription: "Monumento is an AR-integrated social app that transforms how you connect with the world's most iconic landmarks. Through Monumento, you can check in to popular monuments, explore famous sites, and discover new people, all within a social platform.",
    fullDescription: 'Monumento combines Augmented Reality check-ins, landmark discovery, and spatial social networking for travelers and culture lovers.',
    keyFeatures: ['AR Monument Check-Ins & Badges', 'Geofenced Landmark Discovery', 'Traveler Social Feed', 'Offline Map Support'],
    techStack: ['Flutter', 'ARCore', 'ARKit', 'Firebase'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Monumento',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Monumento', label: 'Monumento' }
  },
  {
    slug: 'social-street-smart',
    name: 'Social Street Smart',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'With the adevent of Internet, the problems faced by the people have also grown. These include abusive languages.',
    fullDescription: 'Social Street Smart uses local NLP models to filter cyberbullying, toxic comments, and hate speech on social platforms.',
    keyFeatures: ['On-Device Toxic Language Detection', 'Customizable Blur Controls', 'Privacy-First Local Processing', 'Cross-Platform WebExtension'],
    techStack: ['JavaScript', 'Python', 'WebExtensions API'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Social-Street-Smart',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Social-Street-Smart', label: 'Social-Street-Smart' }
  },
  {
    slug: 'agora-web',
    name: 'Agora Web',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: 'The Agora Web application provides a web interface for running elections using a variety of voting algorithms, built on top of the Agora API.',
    fullDescription: 'Agora Web is the central web dashboard for organizing, auditing, and executing transparent digital elections.',
    keyFeatures: ['Web Voting Dashboard', 'Multi-Algorithm Results Audit', 'Role-Based Admin Controls', 'Agora API Engine'],
    techStack: ['React', 'TypeScript', 'Agora API'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Agora-Web',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Agora-Web', label: 'Agora-Web' }
  },
  {
    slug: 'agora-ios',
    name: 'Agora iOS',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: 'An iOS application for conducting elections using multiple voting algorithms, powered by the Agora Web API backend.',
    fullDescription: 'Agora iOS provides iPhone and iPad users with a native interface to participate in verified voting sessions.',
    keyFeatures: ['Native iOS Swift Interface', 'Biometric Authentication', 'Agora API Integration', 'Offline Ballot Drafts'],
    techStack: ['Swift', 'iOS SDK', 'Agora API'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Agora-iOS',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Agora-iOS', label: 'Agora-iOS' }
  },
  {
    slug: 'openchat-flutter',
    name: 'OpenPeerChat (Flutter)',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: 'A decentralised peer-to-peer chat application built with Flutter, enabling secure and private messaging without a central server.',
    fullDescription: 'OpenPeerChat Flutter brings cross-platform mobile P2P encrypted messaging to Android and iOS devices.',
    keyFeatures: ['Cross-Platform Flutter Engine', 'LibP2P Encrypted Channels', 'Local Device DB Sync', 'No Central Server'],
    techStack: ['Flutter', 'Dart', 'LibP2P'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/OpenPeerChat-flutter',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/OpenPeerChat-flutter', label: 'OpenPeerChat-flutter' }
  },
  {
    slug: 'openchat-react-native',
    name: 'OpenPeerChat (React Native)',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: 'A React Native implementation of the decentralised peer-to-peer OpenPeerChat platform for secure and private messaging.',
    fullDescription: 'OpenPeerChat React Native provides a lightweight JavaScript P2P mobile chat application.',
    keyFeatures: ['React Native Mobile Engine', 'Decentralized P2P Networking', 'Encrypted Key Storage', 'Clean Mobile UI'],
    techStack: ['React Native', 'TypeScript', 'WebSockets'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/OpenPeerChat-react-native',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/OpenPeerChat-react-native', label: 'OpenPeerChat-react-native' }
  },
  {
    slug: 'skeptik',
    name: 'Skeptik',
    category: 'Tools & Utilities',
    status: 'ongoing',
    shortDescription: 'A library and tool for proof compression. Given a proof of a theorem, Skeptik attempts to find a smaller proof of the same theorem.',
    fullDescription: 'Skeptik is an open-source Scala library for structural proof compression, resolution proof transformation, and formal logic optimization.',
    keyFeatures: ['Resolution Proof Compression', 'Structural Logic Transformation', 'Command Line & API Tools', 'Academic Formal Verification Suite'],
    techStack: ['Scala', 'Java', 'Formal Logic'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Skeptik',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Skeptik', label: 'Skeptik' }
  },
  {
    slug: 'sensala',
    name: 'Sensala',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'A dynamic semantics computational linguistics system that interprets natural language sentences using formal semantic techniques.',
    fullDescription: 'Sensala provides formal computational semantics parsing for natural language sentences into mathematical logic formulas.',
    keyFeatures: ['Formal Semantic Sentence Parsing', 'Dynamic Logic Representation', 'Linguistic Tree Extraction', 'Academic NLP Toolkit'],
    techStack: ['Python', 'NLTK', 'Formal Semantics'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/Sensala',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/Sensala', label: 'Sensala' }
  },
  {
    slug: 'carbon-footprint-api',
    name: 'CarbonFootprint API',
    category: 'Sustainability',
    status: 'ongoing',
    shortDescription: 'The backend API powering the CarbonFootprint project, providing carbon emission data and calculations for various activities and services.',
    fullDescription: 'CarbonFootprint API aggregates transportation, flight, and energy emission factors into a lightweight JSON API for developers.',
    keyFeatures: ['RESTful CO2 Calculation Endpoints', 'Open Source Environmental Datasets', 'Caching & Rate Limiting', 'Developer Documentation'],
    techStack: ['Node.js', 'Express', 'JavaScript'],
    logo: '/brand/project_svgs/carbonTracker_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/CarbonFootprint-API',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/CarbonFootprint-API', label: 'CarbonFootprint-API' }
  },
  {
    slug: 'carbon-footprint-mobile',
    name: 'CarbonFootprint Mobile',
    category: 'Sustainability',
    status: 'ongoing',
    shortDescription: 'A mobile application that helps users track and reduce their carbon footprint by monitoring CO2 emissions from everyday activities.',
    fullDescription: 'CarbonFootprint Mobile provides an everyday personal carbon dashboard for smartphones.',
    keyFeatures: ['Personal Carbon Logbook', 'Mode of Transit Detector', 'Offset Goal Analytics', 'Carbon API Sync'],
    techStack: ['React Native', 'JavaScript', 'Carbon API'],
    logo: '/brand/project_svgs/carbonTracker_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/CarbonFootprint-Mobile',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/CarbonFootprint-Mobile', label: 'CarbonFootprint-Mobile' }
  },
  {
    slug: 'crowdalert-web',
    name: 'CrowdAlert Web',
    category: 'Social',
    status: 'ongoing',
    shortDescription: 'A crowdsourced incident reporting web platform that allows users to report and view real-time incidents happening around them.',
    fullDescription: 'CrowdAlert Web visualizes real-time crowdsourced safety alerts and community reports on an interactive map.',
    keyFeatures: ['Crowdsourced Real-Time Map Markers', 'Incident Category Filters', 'Anonymous Reporting Option', 'Geo-Location Alerts'],
    techStack: ['React', 'Leaflet', 'Node.js', 'MongoDB'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/CrowdAlert-Web',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/CrowdAlert-Web', label: 'CrowdAlert-Web' }
  },
  {
    slug: 'debateai',
    name: 'DebateAI',
    category: 'AI & NLP',
    status: 'ongoing',
    shortDescription: 'An AI-powered debate platform that helps users practice and improve their debate skills through structured argumentation and feedback.',
    fullDescription: 'DebateAI provides users with an AI sparring partner that critiques logical fallacies, evaluates argument strength, and offers persuasive speech counterpoints.',
    keyFeatures: ['AI Sparring Debate Engine', 'Logical Fallacy Detection', 'Persuasiveness Score Metrics', 'Speech Audio Transcription'],
    techStack: ['Python', 'React', 'FastAPI', 'LLM APIs'],
    logo: '/brand/icons/aossie_logo.svg',
    githubLink: 'https://github.com/AOSSIE-Org/DebateAI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/AOSSIE-Org/DebateAI', label: 'DebateAI' }
  },
  {
    slug: 'hodlcoin-solidity',
    name: 'hodlCoin (Solidity)',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A decentralised staking platform on EVM chains where users stake tokens to mint hodlTokens. The exchange rate rises as more tokens are staked.',
    fullDescription: 'hodlCoin is an algorithmic staking smart contract where hodlToken exchange rates increase systematically with protocol staking volume.',
    keyFeatures: ['Autonomous Exchange Rate Bonding Curve', 'Staking Rewards Protocol', 'Solidity EVM Contracts', 'Web Dashboard'],
    techStack: ['Solidity', 'React', 'Ethers.js'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/hodlCoin-Solidity-WebUI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/hodlCoin-Solidity-WebUI', label: 'hodlCoin-Solidity-WebUI' }
  },
  {
    slug: 'fairfund',
    name: 'FairFund',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A decentralised funding platform built on Solidity that enables transparent, community-governed allocation of funds to projects and contributors.',
    fullDescription: 'FairFund delivers transparent, quadratic funding smart contracts for open-source initiatives and community grants.',
    keyFeatures: ['Quadratic Funding Smart Contracts', 'Community Voting Verification', 'Milestone Vault Releases', 'DAO Governance Hooks'],
    techStack: ['Solidity', 'React', 'Web3.js'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/FairFund',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/FairFund', label: 'FairFund' }
  },
  {
    slug: 'gluon-ergo-sdk',
    name: 'Gluon Ergo SDK',
    category: 'Infrastructure',
    status: 'ongoing',
    shortDescription: "A TypeScript SDK for interacting with the Gluon protocol on the Ergo blockchain, enabling developers to build applications using Gluon's gold-backed stablecoin system.",
    fullDescription: 'Gluon Ergo SDK allows dApp developers to mint GAU gold stablecoins and interact with ErgoScript contracts programmatically.',
    keyFeatures: ['TypeScript Ergo Contract Bindings', 'Tx Assembly & Signing Helpers', 'Gold Reserve Query API', 'Full Test Suites'],
    techStack: ['TypeScript', 'ErgoScript', 'Node.js'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Gluon-Ergo-SDK',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Gluon-Ergo-SDK', label: 'Gluon-Ergo-SDK' }
  },
  {
    slug: 'gluon-solidity',
    name: 'Gluon (Solidity)',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A Solidity-based implementation of the Gluon protocol providing a gold-backed stablecoin system on EVM-compatible blockchains.',
    fullDescription: 'Gluon Solidity implements gold-pegged stablecoins on EVM networks using reserve ratio balancing mechanisms.',
    keyFeatures: ['EVM Gold Stablecoin Protocol', 'Reserve Vault Smart Contracts', 'Web Dashboard UI', 'Chainlink Oracle Integrations'],
    techStack: ['Solidity', 'React', 'Ethers.js'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Gluon-Solidity-WebUI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Gluon-Solidity-WebUI', label: 'Gluon-Solidity-WebUI' }
  },
  {
    slug: 'gluon-ergo-ui',
    name: 'Gluon Ergo UI',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'The web user interface for the Gluon protocol deployed on the Ergo blockchain, providing access to gold-backed stablecoin operations.',
    fullDescription: 'Gluon Ergo UI is the frontend web dashboard for minting, redeeming, and managing GAU tokens on the Ergo blockchain.',
    keyFeatures: ['Ergo Wallet Connect (Nautilus)', 'GAU Token Minting Interface', 'Gold Reserve Analytics', 'Responsive Dashboard'],
    techStack: ['React', 'TypeScript', 'ErgoScript'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Gluon-Ergo-UI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Gluon-Ergo-UI', label: 'Gluon-Ergo-UI' }
  },
  {
    slug: 'benefaction-platform-ergo',
    name: 'Benefaction Platform (Ergo)',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A decentralised fundraising and benefaction platform built on the Ergo blockchain, enabling transparent community-driven funding campaigns.',
    fullDescription: 'Benefaction Platform Ergo powers decentralized charity and non-profit crowdfunding using Ergo smart contracts.',
    keyFeatures: ['UTXO Smart Contract Crowdfunding', 'Transparent Campaign Tracking', 'Zero Platform Fees', 'Ergo Wallet Integration'],
    techStack: ['ErgoScript', 'React', 'TypeScript'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/BenefactionPlatform-Ergo',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/BenefactionPlatform-Ergo', label: 'BenefactionPlatform-Ergo' }
  },
  {
    slug: 'bene-fundraising-evm',
    name: 'Bene FundRaising (EVM)',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'An EVM-based decentralised fundraising platform allowing projects to raise funds transparently through smart contracts.',
    fullDescription: 'Bene FundRaising EVM brings transparent non-profit crowdfunding to Ethereum, Polygon, and Arbitrum.',
    keyFeatures: ['EVM Crowdfunding Contracts', 'Multi-Stablecoin Grants', 'Verified Recipient Badges', 'Web3 Dashboard'],
    techStack: ['Solidity', 'React', 'Ethers.js'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Bene-FundRaising-EVM-Frontend',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Bene-FundRaising-EVM-Frontend', label: 'Bene-FundRaising-EVM' }
  },
  {
    slug: 'clowder',
    name: 'Clowder',
    category: 'Social',
    status: 'ongoing',
    shortDescription: 'A decentralised platform for organising and managing open-source contributor communities, built on StabilityNexus infrastructure.',
    fullDescription: 'Clowder helps open-source projects organize bounty pools, track contributor reputation, and reward open-source commits.',
    keyFeatures: ['Contributor Reputation Scores', 'Bounty Escrow Vaults', 'GitHub Commit Verification', 'Community Dashboard'],
    techStack: ['React', 'Solidity', 'TypeScript'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Clowder',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Clowder', label: 'Clowder' }
  },
  {
    slug: 'treee',
    name: 'Treee',
    category: 'Sustainability',
    status: 'ongoing',
    shortDescription: 'A blockchain-based platform for planting and tracking trees, enabling transparent environmental impact verification and carbon credit generation.',
    fullDescription: 'Treee verifies tree-planting initiatives on-chain using satellite imagery and IoT sensor data.',
    keyFeatures: ['On-Chain Tree Planting Verification', 'Satellite GIS Integration', 'Environmental Impact NFTs', 'Carbon Credit Minting'],
    techStack: ['Solidity', 'React', 'GIS API'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Treee',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Treee', label: 'Treee' }
  },
  {
    slug: 'hammer-auction-house',
    name: 'Hammer Auction House',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A decentralised on-chain auction house built with Solidity, enabling transparent and trustless bidding for digital and tokenised assets.',
    fullDescription: 'Hammer Auction House enables peer-to-peer auctions for digital and tokenized assets with zero central auctioneer intervention.',
    keyFeatures: ['English & Dutch Auction Mechanics', 'Automated Escrow Asset Release', 'Transparent Bid Logs', 'Low Gas Contract Suite'],
    techStack: ['Solidity', 'React', 'EVM'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/HammerAuctionHouse-WebUI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/HammerAuctionHouse-WebUI', label: 'HammerAuctionHouse-WebUI' }
  },
  {
    slug: 'raindrop',
    name: 'RainDrop',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A decentralised token distribution and airdrop platform built on Solidity, enabling fair and transparent token drops to community members.',
    fullDescription: 'RainDrop lets Web3 projects distribute tokens and rewards to community members with verifiable eligibility criteria.',
    keyFeatures: ['Merkle Tree Proof Verification', 'Batch Token Distribution', 'Anti-Bot Filters', 'Multi-Chain Smart Contracts'],
    techStack: ['Solidity', 'React', 'Ethers.js'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/RainDrop-Frontend',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/RainDrop-Frontend', label: 'RainDrop-Frontend' }
  },
  {
    slug: 'fate-evm',
    name: 'Fate (EVM)',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A prediction market and fate-based gaming platform on EVM chains, enabling decentralised wagering and outcome resolution via smart contracts.',
    fullDescription: 'Fate EVM delivers decentralized prediction markets where users wager on real-world outcomes resolved by decentralized oracles.',
    keyFeatures: ['Prediction Market Smart Contracts', 'Oracle Result Settlement', 'Liquidity Provider Pools', 'Web3 Frontend UI'],
    techStack: ['Solidity', 'React', 'Chainlink'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Fate-EVM-Frontend',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Fate-EVM-Frontend', label: 'Fate-EVM-Frontend' }
  },
  {
    slug: 'hackhub',
    name: 'HackHub',
    category: 'Tools & Utilities',
    status: 'ongoing',
    shortDescription: 'A decentralised hackathon hosting and management platform built on Solidity, providing on-chain prize distribution and project submission tracking.',
    fullDescription: 'HackHub hosts decentralized hackathons with on-chain prize pools, peer judge voting, and immutable project submissions.',
    keyFeatures: ['On-Chain Escrow Prize Pools', 'Peer Judge Voting System', 'Project Submission Records', 'Hackathon Organizer Portal'],
    techStack: ['Solidity', 'Next.js', 'Ethers.js'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/HackHub-WebUI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/HackHub-WebUI', label: 'HackHub-WebUI' }
  },
  {
    slug: 'maelstrom',
    name: 'Maelstrom',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A decentralised vortex-style liquidity and swapping protocol built on Solidity, offering novel AMM mechanics for DeFi participants.',
    fullDescription: 'Maelstrom is an Automated Market Maker (AMM) featuring novel vortex liquidity pools for minimal slippage trading.',
    keyFeatures: ['Vortex Liquidity Pool Mechanics', 'Concentrated Slippage Reduction', 'LP Token Farming', 'Smart Contract Swaps'],
    techStack: ['Solidity', 'React', 'Ethers.js'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Maelstrom-WebUI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Maelstrom-WebUI', label: 'Maelstrom-WebUI' }
  },
  {
    slug: 'chainvoice',
    name: 'Chainvoice',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A blockchain-based invoicing and payment platform that enables transparent, immutable invoice management and settlement on-chain.',
    fullDescription: 'Chainvoice generates cryptographically verifiable invoices with automated on-chain payment reconciliation.',
    keyFeatures: ['Cryptographically Signed Invoices', 'Automated Settlement Verification', 'PDF & CSV Export Tools', 'Multi-Stablecoin Support'],
    techStack: ['Solidity', 'Next.js', 'Ethers.js'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Chainvoice',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Chainvoice', label: 'Chainvoice' }
  },
  {
    slug: 'plaza',
    name: 'Plaza',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A decentralised marketplace built on blockchain technology, enabling peer-to-peer trading of digital assets and services without intermediaries.',
    fullDescription: 'Plaza provides a peer-to-peer decentralized marketplace for trading digital items, software licenses, and crypto assets.',
    keyFeatures: ['Trustless Escrow Trades', 'NFT & Digital Asset Listings', 'Decentralized Dispute Hooks', 'Web3 Wallet Login'],
    techStack: ['Solidity', 'React', 'TypeScript'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Plaza',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Plaza', label: 'Plaza' }
  },
  {
    slug: 'vouchme',
    name: 'VouchMe',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: 'A decentralised reputation and vouching system that allows community members to vouch for each other on-chain, building trust without central authority.',
    fullDescription: 'VouchMe provides decentralized web-of-trust credentialing where community members issue on-chain attestations for peers.',
    keyFeatures: ['On-Chain Trust Attestations', 'Web-of-Trust Graph Analysis', 'Sybil-Resistant Identity Scores', 'Verifiable Credentials'],
    techStack: ['Solidity', 'React', 'TypeScript'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/VouchMe',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/VouchMe', label: 'VouchMe' }
  },
  {
    slug: 'destiny-evm',
    name: 'Destiny (EVM)',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A decentralised on-chain destiny and outcome determination protocol on EVM chains, leveraging verifiable randomness for fair result generation.',
    fullDescription: 'Destiny EVM uses Chainlink VRF and verifiable on-chain randomness to power fair raffles, gaming outcomes, and loot distributions.',
    keyFeatures: ['Verifiable Random Function (VRF) Integrations', 'On-Chain Fair Result Generation', 'Raffle & Gaming Smart Contracts', 'Audit Logs'],
    techStack: ['Solidity', 'React', 'Chainlink VRF'],
    logo: '/brand/project_svgs/stability_nexus_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/Destiny-EVM',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/Destiny-EVM', label: 'Destiny-EVM' }
  },
  {
    slug: 'tnt',
    name: 'TNT',
    category: 'Decentralized',
    status: 'ongoing',
    shortDescription: 'A decentralised token and NFT toolkit built on StabilityNexus infrastructure, providing utilities for token creation, management and distribution.',
    fullDescription: 'TNT delivers decentralized tools for community governance, anti-sybil token distribution, and verifiable digital badge minting across web3 communities.',
    keyFeatures: ['Anti-Sybil Voting Infrastructure', 'Verifiable Governance Token Minting', 'On-Chain Proposal Execution', 'DAO Analytics'],
    techStack: ['Solidity', 'Next.js', 'TypeScript'],
    logo: '/brand/project_svgs/tnt_logo.svg',
    githubLink: 'https://github.com/StabilityNexus/TNT',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/StabilityNexus/TNT', label: 'TNT' }
  },
  {
    slug: 'gluon-ergo-webui',
    name: 'Gluon Ergo WebUI',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'The web dashboard for the Gluon protocol on Ergo, a gold-backed stablecoin system that lets users mint GAU (gold) and GAUC (counter) tokens.',
    fullDescription: 'Gluon Ergo WebUI is the primary interface for managing gold-backed stablecoin minting on the Ergo blockchain.',
    keyFeatures: ['Ergo Nautilus Wallet Integration', 'GAU & GAUC Minting Engine', 'Gold Price Oracle Feeds', 'ErgoScript Interaction'],
    techStack: ['React', 'TypeScript', 'ErgoScript'],
    logo: '/brand/project_svgs/djed_alliance_logo.svg',
    githubLink: 'https://github.com/DjedAlliance/Gluon-Ergo-WebUI',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/DjedAlliance/Gluon-Ergo-WebUI', label: 'Gluon-Ergo-WebUI' }
  },
  {
    slug: 'djed-solidity',
    name: 'Djed Solidity',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'The Solidity smart contract implementation of the Djed algorithmic stablecoin protocol, deployable on any EVM-compatible blockchain.',
    fullDescription: 'Djed Solidity provides EVM-compatible smart contracts for formally verified algorithmic stablecoins.',
    keyFeatures: ['Formally Verified Contracts', 'EVM Multi-Chain Deployments', 'Autonomous Reserve Management', 'Oracle Integration'],
    techStack: ['Solidity', 'Foundry', 'TypeScript'],
    logo: '/brand/project_svgs/djed_alliance_logo.svg',
    githubLink: 'https://github.com/DjedAlliance/Djed-Solidity',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/DjedAlliance/Djed-Solidity', label: 'Djed-Solidity' }
  },
  {
    slug: 'oracle-solidity',
    name: 'Oracle Solidity',
    category: 'Infrastructure',
    status: 'ongoing',
    shortDescription: 'A Solidity-based price oracle system for the DjedAlliance ecosystem, providing reliable on-chain price feeds for stablecoin protocol collateral management.',
    fullDescription: 'Oracle Solidity powers reliable on-chain price aggregation for algorithmic stablecoin collateral vaults.',
    keyFeatures: ['Multi-Source Price Aggregation', 'Decentralized Oracle Nodes', 'Sub-Minute Price Pushes', 'EVM Compatibility'],
    techStack: ['Solidity', 'TypeScript', 'EVM'],
    logo: '/brand/project_svgs/djed_alliance_logo.svg',
    githubLink: 'https://github.com/DjedAlliance/Oracle-Solidity',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/DjedAlliance/Oracle-Solidity', label: 'Oracle-Solidity' }
  },
  {
    slug: 'oracle-backend',
    name: 'Oracle Backend',
    category: 'Infrastructure',
    status: 'ongoing',
    shortDescription: 'The backend service for the DjedAlliance oracle system, responsible for fetching, aggregating, and submitting price data on-chain.',
    fullDescription: 'Oracle Backend fetches real-time exchange rates from top spot exchanges, aggregates price medians, and posts signed transactions to oracle contracts.',
    keyFeatures: ['Exchange API Data Feeds', 'Cryptographic Price Signing', 'High-Availability Node Cluster', 'Sub-Second Off-Chain Aggregation'],
    techStack: ['Node.js', 'TypeScript', 'Ethers.js'],
    logo: '/brand/project_svgs/djed_alliance_logo.svg',
    githubLink: 'https://github.com/DjedAlliance/Oracle-Backend',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/DjedAlliance/Oracle-Backend', label: 'Oracle-Backend' }
  },
  {
    slug: 'stablepay',
    name: 'StablePay',
    category: 'DeFi',
    status: 'ongoing',
    shortDescription: 'A decentralised payment platform that allows merchants and users to transact using stablecoins, providing price-stable crypto payments.',
    fullDescription: 'StablePay enables merchants and users to send and receive crypto payments seamlessly using algorithmic stablecoins.',
    keyFeatures: ['Zero-Intermediary Merchant Settlement', 'Slippage Protection', 'Embeddable Checkout Widget', 'Multi-Currency Support'],
    techStack: ['Solidity', 'React', 'Ethers.js'],
    logo: '/brand/project_svgs/stablepay_logo.svg',
    githubLink: 'https://github.com/DjedAlliance/StablePay',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/DjedAlliance/StablePay', label: 'StablePay' }
  },
  {
    slug: 'gluon-ergo-backend-contracts',
    name: 'Gluon Ergo Backend Contracts',
    category: 'Infrastructure',
    status: 'ongoing',
    shortDescription: 'The Ergo ErgoScript smart contracts powering the Gluon gold-backed stablecoin protocol backend on the Ergo blockchain.',
    fullDescription: 'Gluon Ergo Backend Contracts contain the core ErgoScript UTXO contracts enforcing gold minting ratios and reserve stability.',
    keyFeatures: ['ErgoScript UTXO Smart Contracts', 'Gold Minting & Burn Verification', 'Formal Logic Bounds', 'Ergo Blockchain Engine'],
    techStack: ['ErgoScript', 'Scala', 'Ergo'],
    logo: '/brand/project_svgs/djed_alliance_logo.svg',
    githubLink: 'https://github.com/DjedAlliance/Gluon-Ergo-Backend-Contracts',
    discordLink: 'https://discord.gg/xnmAPS7zqB',
    link: { href: 'https://github.com/DjedAlliance/Gluon-Ergo-Backend-Contracts', label: 'Gluon-Ergo-Backend-Contracts' }
  }
];

export function getAllProjects(): Project[] {
  return PROJECTS_DATA;
}

export function getProjectBySlug(slug: string): Project | undefined {
  return PROJECTS_DATA.find((p) => p.slug.toLowerCase() === slug.toLowerCase());
}

export function getProjectCategories(): string[] {
  const categories = new Set(PROJECTS_DATA.map((p) => p.category));
  return ['All', ...Array.from(categories)];
}
